bin/Punteros : src/Punteros.cpp
	c++ src/Punteros.cpp -o bin/Punteros -Iinclude

ejecutar : bin/Punteros
	./bin/Punteros

bin/ejemplo : src/ejemplo.cpp
	c++ src/ejemplo.cpp -o bin/ejemplo -Iinclude -lftxui-screen

ejemplo : bin/ejemplo
 ./bin/ejemplo

bin/Animacion : src/Animacion.cpp
	c++ src/Animacion.cpp -o bin/Animacion -Iinclude -lftxui-screen

Animacion : bin/Animacion
 ./bin/Animacion